/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in local development and kept here so the
// GitHub-only rebuild has the expected TypeScript project shape.
